version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  nextjs:
    build: .
    container_name: nextjs-container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  mysql_data:
