"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {UserContextProvider} from './../context/UserContext'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
    <html lang="en">
      <body>
        {children}
      <ToastContainer />
       
      </body>
    </html>
    </UserContextProvider>

  );
}
